# Generated by Django 4.0.4 on 2022-04-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250, verbose_name='Name')),
                ('lastname', models.CharField(max_length=250, verbose_name='lastname')),
                ('email', models.EmailField(max_length=254)),
                ('document', models.CharField(max_length=350, verbose_name='Document')),
                ('phone', models.CharField(max_length=30)),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration date')),
            ],
        ),
    ]
