# Generated by Django 4.0.4 on 2022-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employers',
            name='document',
        ),
        migrations.AlterField(
            model_name='employers',
            name='firstname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employers',
            name='lastname',
            field=models.CharField(max_length=250),
        ),
    ]
