# Generated by Django 4.0.4 on 2022-04-18 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0002_remove_employers_document_remove_employers_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_traitement', models.CharField(max_length=500)),
                ('montant_total', models.FloatField(blank=True, null=True)),
                ('montant_a_payer', models.FloatField(blank=True, null=True)),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.employers')),
            ],
        ),
    ]
