# Generated by Django 4.0.4 on 2022-04-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_alter_employers_registrationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
