# Generated by Django 4.0.4 on 2022-04-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_traitement'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='facture',
            field=models.ImageField(blank='true', upload_to='images/'),
        ),
    ]
