# Generated by Django 4.0.4 on 2022-04-19 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_traitement_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='traitement',
            name='registrationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
