# Generated by Django 4.0.4 on 2022-04-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_traitement_date_updated_traitement_registrationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='facture',
            field=models.ImageField(blank='true', null=True, upload_to='images/'),
        ),
    ]
