# Generated by Django 4.0.4 on 2022-04-19 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_alter_traitement_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='facture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
