# Generated by Django 4.0.4 on 2022-04-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_employers_matricule_employers_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='image',
            field=models.ImageField(blank='True', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='employers',
            name='status',
            field=models.CharField(choices=[('Police Nationale/FSSPC', 'Police Nationale/FSSPC'), ('Nationale/DCPAF', 'Nationale/DCPAF')], default='1', max_length=60),
        ),
    ]
