# Generated by Django 4.0.4 on 2022-04-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_employers_image_alter_employers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
