# Generated by Django 4.0.4 on 2022-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0008_alter_employers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='image',
            field=models.ImageField(blank='true', upload_to='images'),
        ),
    ]
