# Generated by Django 4.0.4 on 2022-04-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_alter_employers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='image',
            field=models.ImageField(blank='true', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_traitement', models.CharField(max_length=500)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('montant_a_payer', models.DecimalField(decimal_places=2, max_digits=6)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employers')),
            ],
        ),
    ]
