# Generated by Django 4.0.4 on 2022-04-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0011_alter_traitement_montant_a_payer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='montant_a_payer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='montant_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
